import json
from pathlib import Path

path = Path(__file__).resolve().parents[1] / "landing_translations.json"
data = json.loads(path.read_text(encoding="utf-8"))
translations = {
    "es": {"exploreEyebrow":"Explorar Foundstore","exploreTitle":"Encuentra creadores y paquetes","exploreHint":"Escribe @ para buscar un usuario real de GitHub.","exploreUsers":"Usuarios","explorePackages":"Paquetes","exploreStart":"Empieza con @usuario o con el nombre de un paquete.","exploreSearching":"Buscando usuarios públicos…","exploreNoUsers":"No encontramos usuarios públicos con ese nombre.","exploreNoPackages":"No encontramos paquetes que coincidan.","metricsEyebrow":"El catálogo, con contexto","metricsTitle":"Descubre lo que realmente puedes instalar.","metricsText":"Cifras calculadas desde el catálogo público y actualizadas junto con sus paquetes.","metricPackages":"paquetes publicados","metricCreators":"creadores visibles","metricStars":"estrellas de GitHub","metricPlatforms":"plataformas compatibles","recommendationEyebrow":"Señales verificables","recommendationTitle":"Recomendaciones con origen, no cifras decorativas.","recommendationText":"Cada ficha conserva su creador, su repositorio público y la información que permite decidir antes de instalar.","recommendationQuote":"Explora primero. Instala solo después de revisar el paquete y aprobarlo en tu dispositivo.","recommendationBy":"Equipo de Foundstore","recommendationSource":"Principio de producto"},
    "en": {"exploreEyebrow":"Explore Foundstore","exploreTitle":"Find creators and packages","exploreHint":"Type @ to search for a real GitHub user.","exploreUsers":"Users","explorePackages":"Packages","exploreStart":"Start with @username or a package name.","exploreSearching":"Searching public users…","exploreNoUsers":"No public users found with that name.","exploreNoPackages":"No matching packages found.","metricsEyebrow":"The catalog, with context","metricsTitle":"Discover what you can actually install.","metricsText":"Figures calculated from the public catalog and refreshed with its packages.","metricPackages":"published packages","metricCreators":"visible creators","metricStars":"GitHub stars","metricPlatforms":"compatible platforms","recommendationEyebrow":"Verifiable signals","recommendationTitle":"Recommendations with a source, not decorative numbers.","recommendationText":"Each entry keeps its creator, public repository and the information needed to decide before installing.","recommendationQuote":"Explore first. Install only after reviewing the package and approving it on your device.","recommendationBy":"Foundstore team","recommendationSource":"Product principle"},
    "fr": {"exploreEyebrow":"Explorer Foundstore","exploreTitle":"Trouver des créateurs et des paquets","exploreHint":"Écrivez @ pour rechercher un utilisateur GitHub réel.","exploreUsers":"Utilisateurs","explorePackages":"Paquets","exploreStart":"Commencez par @utilisateur ou le nom d’un paquet.","exploreSearching":"Recherche d’utilisateurs publics…","exploreNoUsers":"Aucun utilisateur public trouvé avec ce nom.","exploreNoPackages":"Aucun paquet correspondant trouvé.","metricsEyebrow":"Le catalogue, avec son contexte","metricsTitle":"Découvrez ce que vous pouvez réellement installer.","metricsText":"Chiffres calculés depuis le catalogue public et actualisés avec ses paquets.","metricPackages":"paquets publiés","metricCreators":"créateurs visibles","metricStars":"étoiles GitHub","metricPlatforms":"plateformes compatibles","recommendationEyebrow":"Signaux vérifiables","recommendationTitle":"Des recommandations avec une source, pas des chiffres décoratifs.","recommendationText":"Chaque fiche conserve son créateur, son dépôt public et les informations utiles avant l’installation.","recommendationQuote":"Explorez d’abord. Installez seulement après avoir vérifié le paquet et l’avoir approuvé sur votre appareil.","recommendationBy":"Équipe Foundstore","recommendationSource":"Principe produit"},
    "de": {"exploreEyebrow":"Foundstore erkunden","exploreTitle":"Entdecke Entwickler und Pakete","exploreHint":"Gib @ ein, um nach einem echten GitHub-Nutzer zu suchen.","exploreUsers":"Nutzer","explorePackages":"Pakete","exploreStart":"Beginne mit @benutzername oder einem Paketnamen.","exploreSearching":"Öffentliche Nutzer werden gesucht…","exploreNoUsers":"Keine öffentlichen Nutzer mit diesem Namen gefunden.","exploreNoPackages":"Keine passenden Pakete gefunden.","metricsEyebrow":"Der Katalog mit Kontext","metricsTitle":"Entdecke, was du wirklich installieren kannst.","metricsText":"Zahlen aus dem öffentlichen Katalog, aktualisiert mit seinen Paketen.","metricPackages":"veröffentlichte Pakete","metricCreators":"sichtbare Entwickler","metricStars":"GitHub-Sterne","metricPlatforms":"kompatible Plattformen","recommendationEyebrow":"Überprüfbare Signale","recommendationTitle":"Empfehlungen mit Quelle statt dekorativer Zahlen.","recommendationText":"Jeder Eintrag bewahrt Entwickler, öffentliches Repository und die Informationen für eine Entscheidung vor der Installation.","recommendationQuote":"Erst erkunden. Installiere erst nach Prüfung des Pakets und lokaler Freigabe auf deinem Gerät.","recommendationBy":"Foundstore-Team","recommendationSource":"Produktprinzip"},
    "pt": {"exploreEyebrow":"Explorar o Foundstore","exploreTitle":"Encontre criadores e pacotes","exploreHint":"Digite @ para buscar um usuário real do GitHub.","exploreUsers":"Usuários","explorePackages":"Pacotes","exploreStart":"Comece com @usuário ou com o nome de um pacote.","exploreSearching":"Buscando usuários públicos…","exploreNoUsers":"Nenhum usuário público encontrado com esse nome.","exploreNoPackages":"Nenhum pacote correspondente encontrado.","metricsEyebrow":"O catálogo, com contexto","metricsTitle":"Descubra o que você realmente pode instalar.","metricsText":"Números calculados a partir do catálogo público e atualizados com seus pacotes.","metricPackages":"pacotes publicados","metricCreators":"criadores visíveis","metricStars":"estrelas do GitHub","metricPlatforms":"plataformas compatíveis","recommendationEyebrow":"Sinais verificáveis","recommendationTitle":"Recomendações com origem, não números decorativos.","recommendationText":"Cada ficha mantém o criador, o repositório público e as informações para decidir antes de instalar.","recommendationQuote":"Explore primeiro. Instale somente depois de revisar o pacote e aprová-lo no dispositivo.","recommendationBy":"Equipe Foundstore","recommendationSource":"Princípio do produto"},
}
for locale in data:
    base = translations.get(locale, translations["en"])
    data[locale].update(base)
path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
