import json
from pathlib import Path

path = Path(__file__).resolve().parents[1] / 'landing_translations.json'
data = json.loads(path.read_text(encoding='utf-8'))
english = {'step1_title':'Connect your account','step1_text':'GitHub identifies your profile and keeps the web catalog separate from your agents’ APIs.','step2_title':'Review the package','step2_text':'Check platform, author, version and Fluthin documentation before continuing.','step3_title':'Approve the action','step3_text':'The linked device receives a request and confirms the installation locally.','trust_eyebrow':'DESIGNED FOR CONTROL','trust_manifest':'Fluthin manifest recognized','trust_compatibility':'Compatibility visible before requesting','trust_approval':'Local approval required','trust_status_label':'status','footer_ecosystem':'Foundstore · Fluthin Ecosystem','footer_platforms':'Danenone · Knosthalij'}
spanish = {'step1_title':'Conecta tu cuenta','step1_text':'GitHub identifica tu perfil y mantiene el catálogo web separado de las APIs de tus agentes.','step2_title':'Revisa el paquete','step2_text':'Consulta plataforma, autor, versión y documentación del Fluthin antes de continuar.','step3_title':'Aprueba la acción','step3_text':'El dispositivo vinculado recibe una solicitud y confirma la instalación de forma local.','trust_eyebrow':'DISEÑADO PARA EL CONTROL','trust_manifest':'Manifiesto Fluthin reconocido','trust_compatibility':'Compatibilidad visible antes de solicitar','trust_approval':'Aprobación local requerida','trust_status_label':'estado','footer_ecosystem':'Foundstore · Ecosistema Fluthin','footer_platforms':'Danenone · Knosthalij'}
german = {'step1_title':'Konto verbinden','step1_text':'GitHub identifiziert dein Profil und hält den Webkatalog von den APIs deiner Agenten getrennt.','step2_title':'Paket prüfen','step2_text':'Prüfe Plattform, Autor, Version und Fluthin-Dokumentation, bevor du fortfährst.','step3_title':'Aktion bestätigen','step3_text':'Das verknüpfte Gerät erhält eine Anfrage und bestätigt die Installation lokal.','trust_eyebrow':'FÜR KONTROLLE ENTWICKELT','trust_manifest':'Fluthin-Manifest erkannt','trust_compatibility':'Kompatibilität vor der Anfrage sichtbar','trust_approval':'Lokale Genehmigung erforderlich','trust_status_label':'status','footer_ecosystem':'Foundstore · Fluthin-Ökosystem','footer_platforms':'Danenone · Knosthalij'}
for locale in data:
    data[locale].update(english if locale not in {'es','de'} else spanish if locale == 'es' else german)
path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print('augmented', len(data), len(english))
